import { Metadata } from "next"

async function getData() {
	const response = await fetch('https://jsonplaceholder.typicode.com/posts')

	return response.json();
}

export const metadata: Metadata = {
	title: 'Blog | Next App',
	description: 'Generated by create next app',
}

export default function Blog() {
	return <h1>Blog page</h1>
}